/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameDenemeleri;

import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author SILA
 */
public class JComboBoxandRadioButton extends javax.swing.JFrame {
    Set<String> set= new LinkedHashSet<>();
    
    public JComboBoxandRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java_radio = new javax.swing.JRadioButton();
        python_radio = new javax.swing.JRadioButton();
        cplus_radio = new javax.swing.JRadioButton();
        göster_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java_radio.setText("Java");

        python_radio.setText("Pyhton");

        cplus_radio.setText("C++");

        göster_butonu.setText("Göster");
        göster_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                göster_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cplus_radio)
                    .addComponent(python_radio)
                    .addComponent(java_radio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(göster_butonu)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(java_radio)
                .addGap(26, 26, 26)
                .addComponent(python_radio)
                .addGap(18, 18, 18)
                .addComponent(cplus_radio)
                .addGap(43, 43, 43)
                .addComponent(göster_butonu)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void show(){
        String message="şu diller seçildi:";
       if(set.isEmpty()==false){
           for(String dil:set){
            message+= dil+" ";
            
        } 
       } 
       else{
             message="dil seçmediniz";  
               }
        JOptionPane.showMessageDialog(this, message);
    }
    private void göster_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_göster_butonuActionPerformed
       if(java_radio.isSelected()){
           set.add("java");
       }
       else{
           set.remove("java");
       }
       if(python_radio.isSelected()){
           set.add("python");
       }
       else{
           set.remove("python");
       }
       if(cplus_radio.isSelected()){
           set.add("c++");
       }
       else{
           set.remove("c++");
       }
       show();
    }//GEN-LAST:event_göster_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JComboBoxandRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JComboBoxandRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JComboBoxandRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JComboBoxandRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JComboBoxandRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cplus_radio;
    private javax.swing.JButton göster_butonu;
    private javax.swing.JRadioButton java_radio;
    private javax.swing.JRadioButton python_radio;
    // End of variables declaration//GEN-END:variables
}
