/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameDenemeleri;


import java.util.LinkedHashMap;

import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author SILA
 */
public class SiparişUygulaması extends javax.swing.JFrame {
     Map<String,Integer> map= new LinkedHashMap<String,Integer> ();
     
    /**
     * Creates new form SiparişUygulaması
     */
    public SiparişUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hamburger_check = new javax.swing.JCheckBox();
        pizza_check = new javax.swing.JCheckBox();
        taco_check = new javax.swing.JCheckBox();
        text_area = new javax.swing.JLabel();
        göster_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiparisUygulaması");

        hamburger_check.setText("Hamburger +150");

        pizza_check.setText("Pizza +200");

        taco_check.setText("Taco +250");

        text_area.setText("Şu diller seçildi:");
        text_area.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                text_areaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                text_areaAncestorRemoved(evt);
            }
        });

        göster_butonu.setText("Göster");
        göster_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                göster_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_area)
                    .addComponent(taco_check)
                    .addComponent(pizza_check)
                    .addComponent(hamburger_check))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(göster_butonu)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(hamburger_check)
                .addGap(18, 18, 18)
                .addComponent(pizza_check)
                .addGap(18, 18, 18)
                .addComponent(taco_check)
                .addGap(27, 27, 27)
                .addComponent(text_area)
                .addGap(18, 18, 18)
                .addComponent(göster_butonu)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void labelDegistir(){
        String message;
        int tutar=0;
        if(map.isEmpty()){
           message="siparişiniz yok";
           setVisible(false);
           
        }
        else{
            message="Siparişler:";
            for(Map.Entry<String,Integer> entry: map.entrySet()){
                message+=entry.getKey()+"\n";
                tutar+=entry.getValue();
            }
            message+="Tutar:"+ tutar;
        }
        JOptionPane.showMessageDialog(this, message);
    }
    private void göster_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_göster_butonuActionPerformed
       if(hamburger_check.isSelected()){
          map.put("hamburger",150);
       }
       else{
           map.remove("hamburger");
       }
       if(pizza_check.isSelected()){
          map.put("pizza",200);
       }
       else{
           map.remove("pizza");
       }
       if(taco_check.isSelected()){
           map.put("taco",250);
       }
       else{
           map.remove("taco");
       }
       labelDegistir();
    }//GEN-LAST:event_göster_butonuActionPerformed

    private void text_areaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_text_areaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_text_areaAncestorAdded

    private void text_areaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_text_areaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_text_areaAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparişUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton göster_butonu;
    private javax.swing.JCheckBox hamburger_check;
    private javax.swing.JCheckBox pizza_check;
    private javax.swing.JCheckBox taco_check;
    private javax.swing.JLabel text_area;
    // End of variables declaration//GEN-END:variables
}
